import { CustomersData, TotalMembers, TypeBookCard } from "@/types";

export const totalMembersData: TotalMembers = [
  {
    date: "Jan",
    "Total members": 945,
  },
  {
    date: "Feb",
    "Total members": 988,
  },
  {
    date: "Mar",
    "Total members": 1002,
  },
  {
    date: "Apr",
    "Total members": 1121,
  },
  {
    date: "May",
    "Total members": 1129,
  },
  {
    date: "Jun",
    "Total members": 1124,
  },
  {
    date: "Jul",
    "Total members": 1084,
  },
  {
    date: "Aug",
    "Total members": 1058,
  },
  {
    date: "Sep",
    "Total members": 1299,
  },
  {
    date: "Oct",
    "Total members": 1501,
  },
  {
    date: "Nov",
    "Total members": 1857,
  },
  {
    date: "Dec",
    "Total members": 1918,
  },
];

export const customersData: CustomersData = [
  {
    customer: "John Smith",
    status: "Enrolled",
    course: "Digital Marketing Fundamentals",
    progress: 65,
  },
  {
    customer: "Emily Johnson",
    status: "Enrolled",
    course: "Social Media Management",
    progress: 45,
  },
  {
    customer: "Michael Brown",
    status: "Enrolled",
    course: "Web Design Basics",
    progress: 20,
  },
  {
    customer: "Jessica Davis",
    status: "Enrolled",
    course: "Content Writing Techniques",
    progress: 75,
  },
  {
    customer: "William Jones",
    status: "Enrolled",
    course: "Graphic Design Essentials",
    progress: 30,
  },
  {
    customer: "Olivia Wilson",
    status: "Enrolled",
    course: "Email Marketing Strategies",
    progress: 10,
  },
  {
    customer: "Daniel Taylor",
    status: "Enrolled",
    course: "UI/UX Design Principles",
    progress: 50,
  },
  {
    customer: "Sophia Martinez",
    status: "Enrolled",
    course: "Search Engine Optimization",
    progress: 90,
  },
  {
    customer: "James Anderson",
    status: "Enrolled",
    course: "Video Editing Fundamentals",
    progress: 15,
  },
  {
    customer: "Isabella Thomas",
    status: "Enrolled",
    course: "E-commerce Strategy",
    progress: 60,
  },
  {
    customer: "David White",
    status: "Enrolled",
    course: "Photography Basics",
    progress: 85,
  },
  {
    customer: "Emma Garcia",
    status: "Enrolled",
    course: "Brand Identity Design",
    progress: 25,
  },
  {
    customer: "Joseph Harris",
    status: "Enrolled",
    course: "Copywriting Techniques",
    progress: 40,
  },
  {
    customer: "Ava Martin",
    status: "Enrolled",
    course: "Social Media Advertising",
    progress: 70,
  },
  {
    customer: "Christopher Clark",
    status: "Enrolled",
    course: "Mobile App Development",
    progress: 5,
  },
  {
    customer: "Mia Rodriguez",
    status: "Enrolled",
    course: "Data Analytics Fundamentals",
    progress: 80,
  },
  {
    customer: "Matthew Lewis",
    status: "Enrolled",
    course: "Video Marketing Strategies",
    progress: 55,
  },
  {
    customer: "Elizabeth Lee",
    status: "Enrolled",
    course: "User Experience Design",
    progress: 35,
  },
  {
    customer: "Andrew Scott",
    status: "Enrolled",
    course: "Web Development Essentials",
    progress: 75,
  },
  {
    customer: "Sofia King",
    status: "Enrolled",
    course: "Creative Writing Workshop",
    progress: 20,
  },
];

export const inQueueBooks: TypeBookCard[] = [
  {
    title: "The Great Gatsby",
    imageUrl: "https://picsum.photos/id/1/120/160",
    author: "F. Scott Fitzgerald",
    date: "2 days ago",
    id: 1,
    authorId: 101,
  },
  {
    title: "To Kill a Mockingbird",
    imageUrl: "https://picsum.photos/id/2/120/160",
    author: "Harper Lee",
    date: "5 days ago",
    id: 2,
    authorId: 102,
  },
  {
    title: "The life is nullish",
    imageUrl: "https://picsum.photos/id/3/120/160",
    author: "George Orwell",
    date: "2 weeks ago",
    id: 3,
    authorId: 103,
  },
  {
    title: "1984",
    imageUrl: "https://picsum.photos/id/4/120/160",
    author: "George Orwell",
    date: "3 weeks ago",
    id: 4,
    authorId: 103,
  },
  {
    title: "Brave New World",
    imageUrl: "https://picsum.photos/id/5/120/160",
    author: "Aldous Huxley",
    date: "1 month ago",
    id: 5,
    authorId: 104,
  },
  {
    title: "The Catcher in the Rye",
    imageUrl: "https://picsum.photos/id/6/120/160",
    author: "J.D. Salinger",
    date: "2 months ago",
    id: 6,
    authorId: 105,
  },
  {
    title: "Pride and Prejudice",
    imageUrl: "https://picsum.photos/id/7/120/160",
    author: "Jane Austen",
    date: "1 week ago",
    id: 7,
    authorId: 106,
  },
  {
    title: "Moby-Dick",
    imageUrl: "https://picsum.photos/id/8/120/160",
    author: "Herman Melville",
    date: "3 weeks ago",
    id: 8,
    authorId: 107,
  },
];

export const BOOKS = [
  {
    id: 1,
    authorId: 101,
    title: "The Great Gatsby",
    isbn: "1933988673",
    pageCount: 416,
    publishedDate: "2 days ago",
    imageUrl: "https://picsum.photos/id/1/600/800",
    shortDescription:
      "Unlocking Android: A Developer's Guide provides concise, hands-on instruction for the Android operating system and development tools. This book teaches important architectural concepts in a straightforward writing style and builds on this with practical and useful examples throughout.",
    status: "PUBLISH",
    authors: "W. Frank Ableson",
    categories: ["Open Source", "Mobile"],
  },
  {
    id: 2,
    authorId: 102,
    title: "To Kill a Mockingbird",
    isbn: "0000000000",
    pageCount: 300,
    publishedDate: "10 years ago",
    imageUrl: "https://picsum.photos/id/2/600/800",
    shortDescription: "A dummy short description for To Kill a Mockingbird.",
    status: "DRAFT",
    authors: "Dummy Author",
    categories: ["Dummy Category"],
  },
  {
    id: 3,
    authorId: 103,
    title: "The life is nullish",
    isbn: "0000000001",
    pageCount: 250,
    publishedDate: "5 years ago",
    imageUrl: "https://picsum.photos/id/3/600/800",
    shortDescription: "A dummy short description for The life is nullish.",
    status: "DRAFT",
    authors: "Dummy Author",
    categories: ["Dummy Category"],
  },
  {
    id: 4,
    authorId: 103,
    title: "1984",
    isbn: "0000000002",
    pageCount: 350,
    publishedDate: "3 years ago",
    imageUrl: "https://picsum.photos/id/4/600/800",
    shortDescription: "A dummy short description for 1984.",
    status: "DRAFT",
    authors: "Dummy Author",
    categories: ["Dummy Category"],
  },
  {
    id: 5,
    authorId: 104,
    title: "Brave New World",
    isbn: "0000000003",
    pageCount: 500,
    publishedDate: "7 years ago",
    imageUrl: "https://picsum.photos/id/5/600/800",
    shortDescription: "A dummy short description for Brave New World.",
    status: "DRAFT",
    authors: "Dummy Author",
    categories: ["Dummy Category"],
  },
  {
    id: 6,
    authorId: 105,
    title: "The Catcher in the Rye",
    isbn: "0000000004",
    pageCount: 400,
    publishedDate: "1 year ago",
    imageUrl: "https://picsum.photos/id/6/600/800",
    shortDescription: "A dummy short description for The Catcher in the Rye.",
    status: "DRAFT",
    authors: "Dummy Author",
    categories: ["Dummy Category"],
  },
  {
    id: 7,
    authorId: 106,
    title: "Pride and Prejudice",
    isbn: "0000000005",
    pageCount: 280,
    publishedDate: "4 years ago",
    imageUrl: "https://picsum.photos/id/7/600/800",
    shortDescription: "A dummy short description for Pride and Prejudice.",
    status: "DRAFT",
    authors: "Dummy Author",
    categories: ["Dummy Category"],
  },
  {
    id: 8,
    authorId: 107,
    title: "Moby-Dick",
    isbn: "0000000006",
    pageCount: 600,
    publishedDate: "6 years ago",
    imageUrl: "https://picsum.photos/id/8/600/800",
    shortDescription: "A dummy short description for Moby-Dick.",
    status: "DRAFT",
    authors: "Dummy Author",
    categories: ["Dummy Category"],
  },
];
